name: Build and Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  APP_NAME: ${{ secrets.APP_NAME }}
  REGION: us-west1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_AUTH0_API_URL=${{ secrets.VITE_AUTH0_API_URL }}" >> .env
          echo "VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}" >> .env
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_PUBLIC_KEY=${{ secrets.VITE_SUPABASE_PUBLIC_KEY }}" >> .env

      - name: Log into Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Run Cloud Build
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.APP_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }} \
            --region ${{ env.REGION }} \
            --port 3000 \
            --allow-unauthenticated
